MAP_LIMITS = 2000 #2000X2000
DELAI = 0.05 #secondes
SCREEN_TYPE = 43
SCREEN_SIZE = 800 # fenetre en 640X640
XCAM_MODIF = 250
YCAM_MODIF = 110
SCREEN_LENGHT = 0
SCREEN_HEIGHT = 0
MUSIC = False
FULLSCREEN = False

fenetre = None
fullscreen = FULLSCREEN
globalLoop = True
menuLoop = True
gameLoop = False
optionsLoop = False
refreshList = []
volume = 50
playlist = ""
hitList = []
playerList = []
refreshNotifList = []
refreshIconlist = []
buttonList = []